---
#------------------------------------------------------------------------------
# install and configure NeoVim
#------------------------------------------------------------------------------

- name: create directories
  become: yes
  file:
    path: "{{ user.home }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group.name }}"
  loop:
    - ".config/nvim/colors"

- name: copy configuration
  become: yes
  copy:
    src: "neovim/{{ item.name }}"
    dest: "{{ user.home }}/.config/nvim/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "{{ user.name }}"
    group: "{{ user.group.name }}"
  with_items:
    - { name: 'init.vim', mode: 'u+rw' }
    - { name: 'colors/nord.vim', mode: 'u+rw' }

- name: add to package list
  set_fact:
    base_package_list: "{{ base_package_list + ['neovim'] }}"
