---
#
# Tasks:
# - Create group
# - Create user
# - Configure fish
#

- name: "Ensure user group exists"
  become: yes
  group:
    name: "{{ user.group.name }}"
    gid: "{{ user.group.id }}"
    state: "present"

- name: "Ensure user exists"
  become: yes
  user:
    name: "{{ user.name }}"
    uid: "{{ user.id }}"
    home: "{{ user.home }}"
    shell: "{{ user.shell }}"
    group: "{{ user.group.name}}"
    groups: 
      - "wheel"
    generate_ssh_key: yes
    ssh_key_type: "{{ user.ssh_key.type }}"
    ssh_key_bits: "{{ user.ssh_key.bits }}"
    ssh_key_file: "{{ user.home }}/{{ user.ssh_key.file }}"
    ssh_key_comment: "{{ user.ssh_key.comment }}"
    state: "present"

- name: "Configuration - create directory"
  become: yes
  file:
    path: "{{ user.home }}/.config/fish/functions"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group.name }}"

- name: "Configuration - copy"
  become: yes
  copy:
    src: "fish/{{ item.name }}"
    dest: "{{ user.home }}/.config/fish/functions/{{ item.name }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: '__bobthefish_colors.fish', mode: 'u+rw' }
    - { name: '__bobthefish_glyphs.fish',  mode: 'u+rw' }
    - { name: 'fish_prompt.fish', mode: 'u+rw' }
    - { name: '__bobthefish_display_colors.fish', mode: 'u+rw' }
    - { name: 'fish_greeting.fish', mode: 'u+rw' }
    - { name: 'fish_title.fish', mode: 'u+rw' }
    - { name: 'bobthefish_display_colors.fish', mode: 'u+rw' }
    - { name: 'fish_mode_prompt.fish', mode: 'u+rw' }

- name: "Add to package list"
  set_fact:
    base_package_list: "{{ base_package_list + ['fish'] }}"
