---
#- name: Get latest release of a public repository
#  github_release:
#    user: inercia
#    repo: k3x
#    action: latest_release
#  register: gh_latest

- name: "Check for latest version"
  uri:
    url: https://api.github.com/repos/helm/helm/releases/latest
    return_content: true
  register: latest_release

- name: "Download and unarchive helm version {{ latest_release.json.tag_name }}"
  unarchive:
    src: "https://get.helm.sh/helm-{{ latest_release.json.tag_name }}-linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: "Copy binary to /usr/local/bin"
  become: true
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    mode: u+rwx,g+rx,o+rx
