---
#------------------------------------------------------------------------------
# WIP
#
#  vars:
#    locale: en_US.UTF-8
#    timezone: America/New_York
#------------------------------------------------------------------------------

- name: set locale
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL=$locale
- name: set /etc/localtime
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link
- name: set /etc/timezone
  template: src=templates/etc/timezone dest=/etc/timezone
  notify: update tzdata
- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
