---
#
# Install and configure waybar
#

- name: create directories
  become: yes
  file:
    path: "{{ user.home }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group.name }}"
  loop:
    - ".config/waybar"

- name: copy configuration
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ user.home }}/{{ item.dest }}"
    owner: "{{ user.name }}"
    group: "{{ user.group.name }}"
  loop:
    - { src: 'waybar/config', dest: '.config/waybar/config' }
    - { src: 'waybar/style.css', dest: '.config/waybar/style.css' }

- name: "Add to package list"
  set_fact:
    sway_package_list: "{{ sway_package_list + ['waybar'] }}"
