---
system:
  arch: "amd64"
  ubuntu_release: "focal"
  slack_version: "4.20.0"
  timezone: "Europe/Berlin"
  locale: "en_US.UTF-8"
  keyboard:
    layout: "us"
    variant: "altgr-intl"
user:
  name: "earthling"
  home: "/home/earthling"
  id: 1177
  shell: "/usr/bin/fish"
  group:
    name: "earthling"
    id: 1177
  ssh_key:
    file: ".ssh/sourcectrl"
    comment: "generated for source control"
    bits: 4096
    type: "ed25519"

