---
#------------------------------------------------------------------------------
# install kubectl
#------------------------------------------------------------------------------

- name: add kubernetes repository
  become: yes
  yum_repository:
    name: kubernetes
    description: Kubernetes repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: add to package list
  set_fact:
    dev_package_list: "{{ dev_package_list + ['kubectl'] }}"
