#
# Install gui tools
#

- import_tasks: alacritty.yml

- import_tasks: wallpaper.yml

- import_tasks: vivaldi.yml

- name: "Ensure package is installed"
  become: yes
  dnf:
    name: "{{ gui_package_list }}"
    state: "present"
    update_cache: yes
