---
#------------------------------------------------------------------------------
# install teams, powershell and visual studio code
#------------------------------------------------------------------------------

- name: add teams repository
  become: yes
  yum_repository:
    name: teams
    description: Microsoft Teams repository
    baseurl: https://packages.microsoft.com/yumrepos/ms-teams
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc


- name: add powershell repository
  become: yes
  yum_repository:
    name: microsoft
    description: Microsoft repository
    baseurl: https://packages.microsoft.com/rhel/7/prod/
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: add visual studio code repository
  become: yes
  yum_repository:
    name: vscode
    description: Visual Studio Code repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: add to package list
  set_fact:
    dev_package_list: "{{ dev_package_list + ['code', 'powershell', 'teams'] }}"

# ToDo:
# - add installation of vscode extensions
#   - ms-azuretools.vscode-docker
#   - golang.go
#   - oderwat.indent-rainbow
#   - ms-kubernetes-tools.vscode-kubernetes-tools
#   - redhat.vscode-yaml
# - add Powershell Azure module
