---
#------------------------------------------------------------------------------
# install terraform
#------------------------------------------------------------------------------

- name: add hashicorp repository
  become: yes
  yum_repository:
    name: hashicorp
    description: Hashicorp Stable
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: add to package list
  set_fact:
    dev_package_list: "{{ dev_package_list + ['terraform'] }}"
