---
#------------------------------------------------------------------------------
# Microsoft
#------------------------------------------------------------------------------

- name: Add APT signing key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
        state: present

- name: Add vscode repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main"
    name: vscode
    state: present

- name: Add teams repository
  become: true
  apt_repository:
    repo: "deb [arch={{ system.arch }}] https://packages.microsoft.com/repos/ms-teams stable main"
    state: present

- name: Add azure-cli repository
  become: true
  apt_repository:
    repo: "deb [arch={{ system.arch }}] https://packages.microsoft.com/repos/azure-cli {{ system.ubuntu_release }} main"
    state: present

- name: Install additional packages
  become: true
  apt:
    pkg:
      - code
      - teams
      - azure-cli
    state: present
