---
#------------------------------------------------------------------------------
# Hashicorp Terraform
#------------------------------------------------------------------------------

- name: Install GPG key
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Install PPA
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ system.ubuntu_release }} main"
    state: present

- name: Install apt package
  become: true
  apt:
    name: "terraform"
    state: present
    update_cache: "yes"
