---
#------------------------------------------------------------------------------
# KeepassXC
#------------------------------------------------------------------------------

- name: Add KeepassXC Repository
  become: true
  apt_repository:
    repo: ppa:phoerious/keepassxc

- name: Install KeepassXC
  become: true
  apt:
    name: keepassxc
    update_cache: yes
    cache_valid_time: 7200
    state: latest
