#
# Install development environment
#

- import_tasks: user.yml

- import_tasks: neovim.yml

- import_tasks: tmux.yml

- name: "Ensure packages are installed"
  become: yes
  dnf:
    name: "{{ base_package_list }}"
    state: "present"
    update_cache: yes
