---
- hosts: all
  tasks:

    - name: "Create user and configure shell"
      import_role:
        name: base
      become_method: sudo

    - name: "Install and configure development tools"
      import_role:
        name: dev
      become_method: sudo

    - name: "Install and configure gui"
      import_role:
        name: kde
      become_method: sudo

