---
#------------------------------------------------------------------------------
# add h264 to firefox
#------------------------------------------------------------------------------

- name: ensure package is installed
  become: yes
  dnf:
    name: "fedora-workstation-repositories"
    state: "present"
    update_cache: yes

- name: enable google chrome
  become: yes
  command:
    cmd: dnf config-manager --set-enabled fedora-cisco-openh264
    warn: false

- name: add to package list
  set_fact:
    kde_package_list: "{{ kde_package_list + ['gstreamer1-plugin-openh264', 'mozilla-openh264'] }}"
