---
#------------------------------------------------------------------------------
# Fedora 35
#------------------------------------------------------------------------------

- hosts: all
  tasks:
    - name: "Set up base configuration"
      import_role:
        name: base
      become_method: sudo
