---
#
# Install and configure sway
#

- name: create directories
  become: yes
  file:
    path: "{{ user.home }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group.name }}"
  loop:
    - ".config/sway"
    - ".swaynag"

- name: copy configuration
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ user.home }}/{{ item.dest }}"
    owner: "{{ user.name }}"
    group: "{{ user.group.name }}"
  loop:
    - { src: 'sway/config', dest: '.config/sway/config' }
    - { src: 'swaynag/config', dest: '.swaynag/config' }

- name: "Add to package list"
  set_fact:
    sway_package_list: "{{ sway_package_list + ['sway', 'swayidle', 'light', 'wl-clipboard', 'network-manager-applet', 'nwg-launchers'] }}"
