---
#
# 
#

- name: create directories
  become: yes
  file:
    path: "{{ user.home }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group.name }}"
  loop:
    - ".config/wallpaper"

- name: copy configuration
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ user.home }}/{{ item.dest }}"
  loop:
    - { src: 'wallpaper/lock.jpg', dest: '.config/wallpaper/lock.jpg' }
    - { src: 'wallpaper/openwiz.png', dest: '.config/wallpaper/openwiz.png' }
    - { src: 'wallpaper/city.jpg', dest: '.config/wallpaper/city.jpg' }
